### ISSUE TITLE
generowanie scenariuszy

### ISSUE THREAD

**Issue by msz13** [msz13/Goal-Based-Investing#9]
Zakres:
- [ ] estymacja parametrów
  - [x] analiza danych historycznych - na podstawie wprowadzonych okresów (srednia ann, std ann, skew, kurtosis, max dropdown, normality test)
  - [ ] estymacja parametrów modelu wybór modeluL MLE/OLS do decyzji
  - [ ] estymacja parametrów modelu MCMC
  - [ ] matryce korelacji między klasami aktywów
- [ ] Kalibracja
  - [ ] generowanie scenariuszy na podstawie parametrów z iwidgets
  - [x] ewaluacja - funchart,  z podsumowaniem percentyli wartości dla różnych okresów
  - [x] ewaluacja - przykładowe n scenariuszy
  - [x] ewaluacja - statystyka charakterystyki, do decyzji - średnie scenariuszy, średnia wartości podsumowań scenariuszy, percentyle
  - [ ] back testing?? np. 2018-2023, szukanie parametrow 1997-2017/1992-2017
  
Aktywa i modele
I Etap - prosty portfel
- [ ] ACWI wartość realna
  - [ ] GBM
    - [ ] MLE/OLs
    - [ ] MCMC 
  - [ ] Regime Switching 
- [ ] EDO
  - [ ] Inflacja oster breacker
  - [ ] Inflacja oster breackerregime switching
  - [ ] z uwzględnieniem stopy procentowej w pierwszym roku
II Etap - złożony porfel  - zakres
 - [ ] EURPLN
 - [ ] USD PLN
 - [ ] Złoto
 - [ ] Obligacje zagraniczne
   - [ ] EURO
   - [ ] USA
 - [ ] akcje 
   - [ ] usa
   - [ ] euro
   - [ ] pln
   - [ ] reszta developme
   - [ ] emerging market
 - [ ] tbsp
  modele:
 - [ ] var model usa (gdp, inflation lr, sr, eq) i dodatkowo (unemployment, consumption, investment)
 - [ ] dfm jw.
 - [ ] var usa, eu, pl 
 - [ ] regresion of internation equities on factors

**Comment by msz13** [comment]
MCMC parameter estimation

najpier dla geometric brownian motion
zrozumieć, co to jest:
- prior distribution
- posterior distribution
- condidat/proposoal distribution 

jak jest probaiblity density function dla GBM

**Comment by msz13** [comment]
Gibs sampling Geometric brownian motion
u - mean of returns
mean ~ N(u, sigma2/T)

**Comment by msz13** [comment]
join multiple scenarios matrix into one:
np.stack((arr1,arr2),axis=2)
shape (T,n_scenarios,number_of_assets)

**Comment by msz13** [comment]
VAR global - zrobic analiza dla usa
i regresje na inne kraje

**Comment by msz13** [comment]
problem z GBM
- okres estymacji paramentrow z msci net - zbyt krotki
- zly rozklad 

co dalej:
- zrobic GBM z gibs sampling
- dokonczyc markov chain monte carlo i zrobic symulacje
- przejsc do modelu var

**Comment by msz13** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/matsz/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/matsz/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


wersja | Equity | fixed income | Alternative | currency
-- | -- | -- | -- | --
I |   |   |   |  
  | pl equity | edo | gold | eurpln
  | developmed market equity | tbsp |   | usdpln
  | emerging market equity | global aggregate |   | jpnpln
II |   |   |   | chnpln
  | Acwi | edo | commodity |  
  | pln equity | tbsp |   |  
  |   | usa long term |   |  
  |   | germany long term |   |  
  |   | swiss long term |   |  
II |   |   |   |  
  | pl equity | tbsp |   |  
  | usa | edo |   |  
  | europe | euro tresaury |   |  
  | japan | usa treasury |   |  
  | pacyfic | global corporate |   |  
  | emerging market equity |   |   |  



</body>

</html>

**Comment by msz13** [comment]
### TODO 26.11.23
- analiza dla transition matrix 1988-2023/2019 i mu/sigma 2023-2023/2019
- analiza dla acwi pln
- mechanizm porownan 
- inflacja bez regimow i z jednym regimem
- zrobic pull request regime switching, lognromal model i evaluation

**Comment by msz13** [comment]
### TODO 26.11.23
#### Poprawi do ewaluacji
- [ ] lepsza parametryzacja, wykresow, np. na podstawie liczby krokow, lat
- [ ] dodanie tytutułów, legend
- [ ] bardziej generyczny raport, np. dla akcji i obligacji, stop procentowych, lub parametryzowany, albo odzielnie - akcje, inflacja, stopy

**Comment by msz13** [comment]
### TODO
#### Uporządkować projekt
Scenariusz:
- implementacja modoeli
- implementacja estymacji parametrow
- implementacja narzędzi ewaluacji
- przerowadzenie analizy

**Comment by msz13** [comment]
### Do czytania 26

- low expeted returns
- ortec methodology
- magisterka alm z ortec scenarios
- strategic assets alm (uzycie var models)
- regime switching gibs sampling
- magisterka goscia z ortec
- gosciu z ortec views
- szukac o kalibracji

**Comment by msz13** [comment]
regime switching model ma rożne parametry w róznych okresach , 
male roznice w parametrqch powoduje niewielkie roznice w skumulowanych zyskach, natomaist duze duze (jak duze)
przyszlosc, niedzwieciedla przeszlosci trzeba dobrac odpoweidnie parametry 
(moze korekcja danych historycznych, np. odjecie od historycznych stow zwrotów jakies sumy)

jak wygladaja parametry i jaka jest stabilnosc przy mcmc

jaka jest relacja miedzy konserwatywnymi zalozeniami modelu, co sie dzieje gdy przyjme zbyt konserwatynwe zalozenia dla ryzyka i celu

jakie sa moje oczekiwania na 10 i 20 lat

maksymalny horysont to 25 lat, przy dluzszym blad w estymacji parametrow sie kumuluje

co robic
kontynuowac z regime switching model, - baye, wybrac dobry okres, wybrac 4 regimy (kryzys, revovery, slow growth, high growth)
porzuccic i pobawiac sie z var modelem i pokrewnymi, lub ortec methodology, views, itd 
poszukac z mean reverting long run

jak sa moje oczekiwania do rozkaldow srednich stop zwrotu (10,25,50)

**Comment by msz13** [comment]
- TODO 
- uporzadkowac excel (w tym ograniczenie do 25 lat) lub zrobic alternatywe w skrypcie

**Comment by msz13** [comment]
####conning

us rf => usa -> eafe -> em -> wig
us yeld -> us bond index -> int bond index

pln cpi -> edo
pln -> tbsp

usdpln heston model (us rf - pln risk free)

korelacja miedzy tbsp a wig
korelacja miedzy tbsp a us bond i int bond
korelacja edo -> int

przy acwi i edo mozna tak zrobic, bo nie trzeba zakładac korelacji, 
gdy chcemy polska stope procentowa, to musimy zrobic korelacje miedzy stopami pln i usa, i waluta
moze tez byc wig excess return regression on foreign index

####lub wersja odwrotna
pln inflation -> stopy -> akcje -> regresja foreign na polskim modelu

**Comment by msz13** [comment]
Waluty:
- problem, ze dostepne tylko od 1999/2003 roku
- zrobić odrebna symulacje waluty
- zrobic backfilling danych
- przejsc na model var
- znalezc okres po 2000 z podobnymi parametrami

**Comment by msz13** [comment]
var model:

- najpier usa dlug okres, potem krotki, 
- sprawdzic 
- potem dodac inflacje pln, 
- odac europę od 1999

zlaeznosci :
- wszystkie czynniki fundamentalne analizowac razem, gdy nie wyjdzie, 
- to odzielnie  i tlyko korelacje zrobic miedzy nimi
- doadc polskce od 1999 jako regresje do gospodarek swiatowych

**Comment by msz13** [comment]
zrobic analize acwi pln dla 
03 2000 – 12 2021 – od szczytu do szczytu
09.2002 – 09.2022
09.2002  –  02.2020

**Comment by msz13** [comment]
zrobic regresje spp wobec wig i odwrotna

**Comment by msz13** [comment]
problem:
- potrzebne są kryteria akceptacyjne - target levels dystrybucji wyników
- okres acwi jest wbyt mały, aby je okreslić 
- powinno się zrobić analize usa (długi okres danych) i regresje innych rynków

jakby sie chcialo wykorzystac model cas, to trzeba zrobic model waluty, a do tego potrzbne sa roznice w stopach procentowych

**Comment by msz13** [comment]
Cele i kryteria akceptacji:
1. Realistyczne percentyle stopy zwrotu po x latach
2. Realistyczne prawdopodobieństwo drop down - zabezpieczenie przed ryzykiem ostatnich latch
3. Korelacje między klasami - do oszacowanie efficient frontier
4. 
Czy mają uwzględniać obecną sytuację rynkową?

**Comment by msz13** [comment]
usd pln

modele do rozwazenia
- brownian motion skorelowany z akcjami
- regime switching brownian motion - jak oszacowac parametry: wziac states z akcji i oszacowac parametry, albo znalezc jakims model wspolnego szacowania
- regresja na akcje - sprawdzic
- interest rate parity - trudniejsze

**Comment by msz13** [comment]
rozszerzenie prostego modelu
- risk free rate
- price
- dividend
- regresja na developed i emerging

**Comment by msz13** [comment]
[model single variable.docx](https://github.com/msz13/Optymalizacja-portfela/files/13684835/model.single.variable.docx)

**Comment by msz13** [comment]
TODO??

- zrobić experyment z vanguard model
- czy esklorować temat z regime switching

**Comment by msz13** [comment]
Aktualny stan:
- prognoza cape jest bez sensu, rozjezdza się z aktualna, ale moze jednak sprawdzic ostateczna cene?
- szukanie regime switching do targetu nie wyszlo, sprawdzic funkcje podstawowa i wyrzucic do kosza pomysl
- od 10 lat, moze krocej?, gbm ma takie same wyniki jak RS
- zrobic model dywidendy
- zrobic model inflacji pl
- zrobic model stopy procentowej usa?

**Comment by msz13** [comment]
bootstrap vs overlapping 
im mniejszy okres w gropu bootrap, tym niejsze 25 percentyl, im wiekszy tym wkeszy 25% percentyl

**Comment by msz13** [comment]
data = np.arange(1,48, dtype=int)
#bootstrap


def block_bootstrap(data, block_length, num_blocks, n_samples):

    index_range = np.arange(len(data)-block_length)

    resampled = np.zeros((n_samples,block_length*num_blocks))

    for s in range(n_samples):
        for block in range(num_blocks):    
            index = np.random.choice(index_range)
            sample = data[index:index+block_length]
            resampled[s,block*block_length:(block+1)*block_length] = sample

    return resampled



block_bootstrap(data,6,2,2)

**Comment by msz13** [comment]
'''
data = np.arange(1,48, dtype=int)
#bootstrap


def block_bootstrap(data, block_length, num_blocks, n_samples):

    index_range = np.arange(len(data)-block_length)

    resampled = np.zeros((n_samples,block_length*num_blocks))

    for s in range(n_samples):
        for block in range(num_blocks):    
            index = np.random.choice(index_range)
            sample = data[index:index+block_length]
            resampled[s,block*block_length:(block+1)*block_length] = sample

    return resampled



block_bootstrap(data,6,2,2)
'''

**Comment by msz13** [comment]
porownanie modeli dlasp500


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MSZCZE~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MSZCZE~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


  | llf | aic | bic |  
-- | -- | -- | -- | --
AR | 6 | 6 | 6 | 18
regime2 | 5 | 5 | 1 | 11
regime3 | 4 | 4 | 3 | 11
regime4 | 2 | 3 | 4 | 9
ARregime3 | 3 | 1 | 2 | 6
ARregime4 | 1 | 2 | 5 | 8



</body>

</html>

**Comment by msz13** [comment]
inflacja 

- dane wejsciwe 
  -  cpi = skumulowany (1+r inflacji)
  -  ln(cpi t/ cpi t-1)

**Comment by msz13** [comment]
pln cpi calibration target:
mean: 2,5%
percentule 97,5% - 16%
2% - 1%

**Comment by msz13** [comment]
### problemy z polska inflacja:
-  krótkie okres polskich danych
-  duża inflacja 2021-2022 - która nie może wyjść na podstawie prostego modelu

krótki okres nie byłby problemem, gdyby nie ta duza inflacja

możliwe rozwiązania:
* wspólny stan oparty  twarde dane, np. o regimy monetarne Begin, obliczanie prawdopodobieństwa na podstawie państwa rozwiniętych
* inflacja jako AR(1) proces z egzegonous variable - inflacja USA lub Niemcy
* dodać wspólny jump process - kryzysowe sprawy

**Comment by msz13** [comment]
zaleznosc:
- jesli bedzie duza inflacja, to cena dlorara wzrosnie, i wzrosnie stopa zwrotu z zagranicznych intrumentow
- czyli realna stopa zwrotu pozostanie taka sama

**Comment by msz13** [comment]
prosty model:
- polska giełda - gbm
- tbsp - w oparciu o stopy procentowe

**Comment by msz13** [comment]
https://medium.com/@polanitzer/estimating-the-parameters-for-a-geometric-brownian-motion-stochastic-process-using-two-different-6c7cbdf20c8f

**Comment by msz13** [comment]
Global scenarios
https://www.actuaries.org/AFIR/Colloquia/Nuernberg/Mulvey_Thorlacius.pdf

**Comment by msz13** [comment]
edo

edo = [1:10]

edo_ret[stage % 10] = yield[stage]
edo_ret[1:stage % 10 - 1] = inflation_last +premium
inflation_last.out = inflation[stage]

edo.out = edo.in .* edo_ret + edo_buy(tylko dla etgo stage) + edo_sell(dla wszystkich)

**Comment by msz13** [comment]
Albo:
-	Inflacja Ar + raal acwi – baye based od pln
-	Inflacja AR + realne aktywa w pln HMM
-	Własny model symulacji + scenario lattice based on reduction


Problem z HMM
Dane w pln tylko z 20 lat.
Nie wiem, jak zamienić model miesięczny na roczny

Czy iść w scenario lattice, czy w regime switching

**Comment by msz13** [comment]
Ewaluacja scenariuszy:
- conserwatyzm - analiza upper i lower 5% percentiles - tylko nie wiadomo, czy wiekszy, to lepszy - bardziej określic trzeba target
- forecast - rmse z realnymi wynikami
- covarege - czy realne wyniki przynależą do 90% confidence interval
